### ISSUE TITLE
[bug]: React 19 forwardRef warnings

### ISSUE THREAD

**Issue by RDIL** [shadcn-ui/ui#3898]
### Describe the bug

React 19 has deprecated forwardRef - that means that these components will need to be modified in order to stop the deprecation warnings. The replacement is just to pass ref as a prop.

### Affected component/components

Almost all

### How to reproduce

Use next.js canary and open browser console

### Codesandbox/StackBlitz link

https://github.com/vercel/next.js

### System Info

```bash
N/A
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by hawkdevelopers** [comment]
Same error here :(

**Comment by pavelbe** [comment]
I have the same error. When will this be fixed? I want to practice Nextjs 15 (rc) + shadcn ui !

**Comment by Thijs-Lambert** [comment]
Radix needs to be React 19 ready first. Which is happening right now with https://github.com/radix-ui/primitives/pull/2934.
Shadcn/ui will probably follow shortly after.

**Comment by vladmoroz** [comment]
This is fixed in the new release candidate versions – please upgrade to the latest rc’s

**Comment by CarlosZiegler** [comment]
Radix React 19 compatibility RC => https://github.com/radix-ui/primitives/pull/2934

**Comment by ZeyadZewail** [comment]
Does anyone know how to migrate my components while preserving my changes to them? using CLI again would overwrite them.

I tried using the codemod but that didn't fix the errors like using the radix-RC does.

**Comment by aleciavogel** [comment]
> Does anyone know how to migrate my components while preserving my changes to them? using CLI again would overwrite them.
> 
> I tried using the codemod but that didn't fix the errors like using the radix-RC does.

@ZeyadZewail  Refer to my PR (#4356) for how I've updated all of the components. Here's a summary of how I approached these changes.

### Steps to Migrate Your Components:

1. **Remove forwardRef**: You no longer need to wrap your component with forwardRef.
2. **Use React.ComponentProps for Typing:** Instead of manually defining the prop types, use `React.ComponentProps` to automatically include the `ref` and other props.
3. **Remove Redundant `ref` Prop:** Since ref is now included in props, you don’t need to explicitly pass `ref={ref}`.

#### Example of Standard HTML component

**Before:**

```typescript
const CardHeader = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div ref={ref} className={cn("flex flex-col space-y-1.5 p-6", className)} {...props} />
));
```

**After:**
```typescript
/**
 * Note: Replace "div" with the tag being returned (ie, "tr" for a table row)
 */
const CardHeader: React.FC<React.ComponentProps<"div">> = ({
  className,
  ...props
}) => (
  <div className={cn("flex flex-col space-y-1.5 p-6", className)} {...props} />
);
```

#### Example of Radix component wrapper

**Before:**
```typescript
/**
 * Note: instead of an HTML tag, this time you'll use the type 
 * defined in `React.ComponentPropsWithoutRef`
 */
const Checkbox = React.forwardRef<
  React.ElementRef<typeof CheckboxPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof CheckboxPrimitive.Root>
>(({ className, ...props }, ref) => (
  <CheckboxPrimitive.Root ref={ref} className={cn(className)} {...props} />
));
```

**After:**
```typescript
const Checkbox: React.FC<
  React.ComponentProps<typeof CheckboxPrimitive.Root>
> = ({ className, ...props }) => (
  <CheckboxPrimitive.Root className={cn(className)} {...props} />
);
```

> [!Warning]  
> You should not remove the `ref={ref}` line from the `ChartTooltipContent` or `ChartLegendContent` components unless you have modified them to spread the `props` (ie, `{...props}`) on the same child element where `ref={ref}` would be. For these components, add `ref` to the deconstructed props and keep the `ref={ref}` line in. [Refer to my changes here](https://github.com/shadcn-ui/ui/blob/419ccaa17b50f952a217d9759fc967ed8442a51c/apps/www/registry/default/ui/chart.tsx#L127) to see what I mean.

**Comment by gavan1** [comment]
@aleciavogel Thank you for those tips but I am still getting some errors. Could you advise on this particular [example](https://www.radix-ui.com/primitives/docs/components/navigation-menu)? from radix-ui website?

@CarlosZiegler will running `pnpm add radix-ui/primitives@1910a8c` be enough to use the navigation menu? Or are there any additional steps?


```
const ListItem = React.forwardRef(({ className, children, title, ...props }, forwardedRef) => (
  <li>
    <NavigationMenu.Link asChild>
      <a className={classNames('ListItemLink', className)} {...props} ref={forwardedRef}>
        <div className="ListItemHeading">{title}</div>
        <p className="ListItemText">{children}</p>
      </a>
    </NavigationMenu.Link>
  </li>
```

**Comment by aleciavogel** [comment]
I'm not 100% sure. I'll take a look tomorrow and see if I can figure it out.

**Comment by gavan1** [comment]
@aleciavogel Thanks you! 
Could help clarify the following for the MenuMenu Component?
No error on compile but tsx linter has the following issue with the `<a>`




```
const ListItem: React.FC<React.ComponentProps<typeof NavigationMenu.Link>> =({className, children, title, ...props }) =>(
  <li>
    <NavigationMenu.Link asChild> 
      <a className={classNames('ListItemLink', className)} {...props} >
        <div className="ListItemHeading">{title}</div>
        <p className="ListItemText">{children}</p>
      </a>
    </NavigationMenu.Link>
  </li>
);
```

![Screen Shot 2024-09-09 at 9 00 59 AM](https://github.com/user-attachments/assets/7946f9e6-36b4-4cc1-accb-f24eddf797ce)

**Comment by uncvrd** [comment]
@aleciavogel thanks for the helpful intro into ComponentProps! Looks like the jsdoc for that type recommends using more specific `ComponentPropsWithRef` or `ComponentPropsWithoutRef`

just thought I'd add!

<img width="979" alt="image" src="https://github.com/user-attachments/assets/04a63955-8e34-47d8-bd84-3cfbebfcaadc">

**Comment by aleciavogel** [comment]
> @aleciavogel thanks for the helpful intro into ComponentProps! Looks like the jsdoc for that type recommends using more specific `ComponentPropsWithRef` or `ComponentPropsWithoutRef`
> 
> just thought I'd add!
> 
> <img width="979" alt="image" src="https://github.com/user-attachments/assets/04a63955-8e34-47d8-bd84-3cfbebfcaadc">
> 

Thanks for this info! Just waking up and will take a look later today

**Comment by chukwumaokere** [comment]
Just to check, theres no easy way to upgrade all my shadcn components right? I have to make these changes all manually? Theres no codemod or something to facilitate this?

**Comment by shadcn** [comment]
Hi. We're closing some old issues as outdated. If this is still relevant, leave a message, we'll reopen it. Thank you. Appreciate your contribution to the project - shadcn
