### ISSUE TITLE
[bug]: toggle in tooltip is not working

### ISSUE THREAD

**Issue by fredle09** [shadcn-ui/ui#4185]
### Describe the bug

I have this code:
```
<TooltipPrivoder>
  <Tooltip>
    <TooltipTrigger asChild>
      <Toggle
        variant="outline"
        aria-label="Toggle love"
        className="pl-2.5"
      >
        <HeartPlusIcon className="h-6 w-6 mr-2" />
        Love
      </Toggle>
    </TooltipTrigger>
    <TooltipContent side="bottom">
      <span>Love this event</span>
    </TooltipContent>
  </Tooltip>
</TooltipPrivoder>
```

Not my toggle is not working. And my temporary solution is not to use `asChild` property in `TooltipTriger`, but it will come to another problem which is `<button>` in `<button>`.

### Affected component/components

Tooltip, Toggle

### How to reproduce

Just import tooltip, and toggle, and use them like the code above

### System Info

```bash
Chrome, Edge
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by Abhi-6284** [comment]
<TooltipProvider>
        <Tooltip>
          <TooltipTrigger className="ml-5">
            <Toggle
              variant="outline"
              aria-label="Toggle love"
              className="pl-2.5"
            >
              <Heart className="h-4 w-4" />&nbsp;Heart
            </Toggle>
          </TooltipTrigger>
          <TooltipContent side="bottom">
            <span>Bold</span>
          </TooltipContent>
        </Tooltip>
      </TooltipProvider>
 
// Code     
<img width="522" alt="Screenshot 2024-07-06 at 4 48 44 PM" src="https://github.com/shadcn-ui/ui/assets/108335288/9664c558-db90-4a58-8b7a-81d30ff62abd">

// Click
<img width="671" alt="Screenshot 2024-07-06 at 4 49 11 PM" src="https://github.com/shadcn-ui/ui/assets/108335288/196209d1-9971-4ed2-a5ea-d919fc98ace2">

// Hover
<img width="745" alt="Screenshot 2024-07-06 at 4 51 12 PM" src="https://github.com/shadcn-ui/ui/assets/108335288/eb014086-3838-40e2-b1f2-b83f2fc25ab0">

      Check this will work
      
      
      In you code 
      <TooltipPrivoder> // Spelling Mistake  --> TooltipProvider
  <Tooltip>
    <TooltipTrigger asChild>
      <Toggle
        variant="outline"
        aria-label="Toggle love"
        className="pl-2.5"
      >
        <HeartPlusIcon className="h-6 w-6 mr-2" />
        Love
      </Toggle>
    </TooltipTrigger>
    <TooltipContent side="bottom">
      <span>Love this event</span>
    </TooltipContent>
  </Tooltip>
</TooltipPrivoder>

**Comment by fredle09** [comment]
Thank you for your help. But, as I mentioned above, when using `asChild` in `<TooltipTrigger>`, the `<Toggle>` doesn't work. And when not using `asChild`, `<button>` in `<button>`, as shown below.

![Screenshot (36)](https://github.com/shadcn-ui/ui/assets/54971686/cf8c910f-e522-4b83-961f-0f97dbc0e72b)

According to my research, it's because `<TooltipTrigger>` and `<Toggle>` both use the `data-state` field to manage their status.
- For `<TooltipTrigger>`, it is `data-state="close"`, and `data-state="delayed-open"`.
- For `<Toggle>`, it is `data-state="on"`, `data-state="off"`.

And when using `asChild`, `<TooltipTrigger>`'s `data-state` will overwrite `<Toggle>`'s `data-state`, making `<Toggle>`'s `data-state` unsatisfactory.


Therefore, to completely solve this problem, the `data-state` field of one of the two components above must be changed.

**Comment by henrygd** [comment]
Using `asChild` and wrapping `<Toggle>` in a span seems to work for me.

**Comment by nikita-mishchenko** [comment]
Hi @shadcn, 

Are there any updates on this one? The save valid not only for `Toggle` component, but many other as well. And seems like the reason is well described by @fredle09 comment above. Thanks

**Comment by Ganbin** [comment]
Hi, I believe to have a similar issue when using the `sidebar` component.

When I use `SidebarMenuButton` with `asChild` : 
```jsx
<SidebarMenuButton tooltip={item.title} asChild>
  <NavLink to={item.url}>
    {item.icon && <item.icon />}
    <div>{item.title}</div>
  </NavLink>
</SidebarMenuButton>
```

it makes the tooltip not to show when the sidebar is collapsed.

To fix it I had to change the `SidebarMenuButton` component from: 

```tsx
<TooltipTrigger asChild>{button}</TooltipTrigger>
```

to

```tsx
<TooltipTrigger>{button}</TooltipTrigger>
```

**Comment by bukacdan** [comment]
>  But, as I mentioned above, when using asChild in <TooltipTrigger>, the <Toggle> doesn't work. And when not using asChild, <button> in <button>, as shown below.

This is a problem because 
```
In HTML, cannot be a descendant of button. This will cause a hydration error.
```

**Comment by C3ntraX** [comment]
This worked too:

```
   <ToggleGroup
      >
        <TooltipProvider>
          <Tooltip>
            <TooltipTrigger asChild>
              <span>
                <ToggleGroupItem className="[&_svg]:size-5" value="...">
                  <HistoryIcon />
                </ToggleGroupItem>
                <span></span>
              </span>
            </TooltipTrigger>
            <TooltipContent className="whitespace-pre-line">
              <Label>...</Label>
            </TooltipContent>
          </Tooltip>
        </TooltipProvider>
        <TooltipProvider>
          <Tooltip>
            <TooltipTrigger asChild>
              <span>
                <span></span>
                <ToggleGroupItem className="[&_svg]:size-5" value="...">
                  <SquareSplitHorizontalIcon />
                </ToggleGroupItem>
              </span>
            </TooltipTrigger>
            <TooltipContent className="whitespace-pre-line">
              <Label>...</Label>
            </TooltipContent>
          </Tooltip>
        </TooltipProvider>
      </ToggleGroup>
```

**Comment by shadcn** [comment]
Hi. We're closing some old issues as outdated. If this is still relevant, leave a message, we'll reopen it. Thank you. Appreciate your contribution to the project - shadcn

**Comment by saevarb** [comment]
> Hi. We're closing some old issues as outdated. If this is still relevant, leave a message, we'll reopen it. Thank you. Appreciate your contribution to the project - shadcn

As far as I can tell, this is still a real issue in that tooltips do not work properly with `ToggleGroup` or rather `ToggleGroupItem`. The tooltips are shown, the toggling works but the toggle state is not shown in the toggle group.

```tsx
              <Tooltip>
                <TooltipTrigger asChild>
                  <ToggleGroupItem value="show_timestamps">
                    <ClockIcon />
                  </ToggleGroupItem>
                </TooltipTrigger>
                <TooltipContent>Show timestamps</TooltipContent>
              </Tooltip>
```

A blessed workaround would be useful as well. For the record, the `<span>` workaround does not work, as it breaks the styling of the group:

<img width="115" height="57" alt="Image" src="https://github.com/user-attachments/assets/fd0f08f2-f173-4090-a8c6-a4d306ffc03a" />

**Comment by C3ntraX** [comment]
Yeah, still annoying.

```
<Tooltip>
                <TooltipTrigger asChild>
                   <span> // <---
                  <ToggleGroupItem value="show_timestamps">
                    <ClockIcon />
                  </ToggleGroupItem>
                 </span>
                </TooltipTrigger>
                <TooltipContent>Show timestamps</TooltipContent>
              </Tooltip>
```

But the issue is that the borders radius classes are then wrong applied.

I fixed it like this:
```
    <span>
      <ToggleGroupPrimitive.Item
        data-slot="toggle-group-item"
        data-variant={context.variant || variant}
        data-size={context.size || size}
        ref={ref}
        className={cn(
          toggleVariants({
            variant: context.variant || variant,
            size: context.size || size
          }),
          'min-w-0 flex-1 border-border shrink-0 whitespace-nowrap rounded-none shadow-none focus:z-10 focus-visible:z-10 data-[variant=outline]:border-l-0 ',
          !mode && 'first:rounded-l-md last:rounded-r-md data-[variant=outline]:first:border-l',
          mode === 'first' && 'rounded-l-md data-[variant=outline]:border-l',
          mode === 'middle' && 'data-[variant=outline]:border-l-0',
          mode === 'last' && 'rounded-r-md',
          className
        )}
        {...props}
      >
        {children}
      </ToggleGroupPrimitive.Item>
    </span>
```

But setting the directions manually shouldn't be neccesarry tbh

**Comment by dhanushtheijas08** [comment]
The problem still exists. I feel using `DataStatePropInterceptor`, as suggested by @tomgreeEn, is the best way to handle this. Switching to a plain `span` could break accessibility.

**Comment by bavjackson** [comment]
This seems to be affecting button groups as well.
