### ISSUE TITLE
[bug]: react-day-picker 9.0.0 release screws up Calendar component

### ISSUE THREAD

**Issue by gregpr07** [shadcn-ui/ui#4366]
### Describe the bug

![CleanShot 2024-07-21 at 17 46 51@2x](https://github.com/user-attachments/assets/81909edc-30ed-4b67-8ce7-3f93463b02e7)

Currently, the component looks like this.

**Fix:**
You can currently fix this by downgrading react-day-picker to version 8.^

### Affected component/components

Calendar, Date Picker, ...

### How to reproduce

1. Install Calendar component

### System Info

```bash
Browsers
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by Cheveniko** [comment]
Easiest solution right now is to downgrade to 8.10.1.
The react-day-picker team has already been notified of this issue [in the v9.0.0 release announcement](https://github.com/gpbl/react-day-picker/discussions/2280#discussioncomment-10106146)

**Comment by grzegorzpokorski** [comment]
Here are my adjusted styles for the Calendar component:
https://github.com/grzegorzpokorski/calendar-shadcnnui/blob/main/src/components/ui/calendar.tsx.
Maybe someone will have more time to review them and improve.

**Comment by efgomes** [comment]
OK, I'm using your code. When making adjustments to my code and not finding another solution for positioning the navigation buttons, I used the z-index

**Comment by efgomes** [comment]
> Here are my adjusted styles for the `Calendar` component: https://github.com/grzegorzpokorski/calendar-shadcnnui/blob/main/src/components/ui/calendar.tsx. Maybe someone will have more time to review them and improve.
> 
> The most intriguing aspect is the change in the structure of this component, particularly the navigation between months. I am not sure if the current design is appropriate (playing with `z-index`).

OK, I'm using your code. When making adjustments to my code and not finding another solution for positioning the navigation buttons, I used the z-index

**Comment by danielmari2** [comment]
> Easiest solution right now is to downgrade to 8.10.1. The react-day-picker team has already been notified of this issue [in the v9.0.0 release announcement](https://github.com/gpbl/react-day-picker/discussions/2280#discussioncomment-10106146)

I still have same error after downgrading

**Comment by NamorAgro** [comment]
same bug ((

**Comment by NamorAgro** [comment]
> Easiest solution right now is to downgrade to 8.10.1. The react-day-picker team has already been notified of this issue [in the v9.0.0 release announcement](https://github.com/gpbl/react-day-picker/discussions/2280#discussioncomment-10106146)

npx shadcn-ui@8.10.1 add calendar
gives error, no such version matching

**Comment by olsio** [comment]
> > Easiest solution right now is to downgrade to 8.10.1. The react-day-picker team has already been notified of this issue [in the v9.0.0 release announcement](https://github.com/gpbl/react-day-picker/discussions/2280#discussioncomment-10106146)
> 
> npx shadcn-ui@8.10.1 add calendar gives error, no such version matching

The dependency is on react-day-picker. Go to your package.json and set the 8.10.1 there and then run npm install

**Comment by flixlix** [comment]
fixed here https://github.com/shadcn-ui/ui/pull/4421

**Comment by huybuidac** [comment]
While waiting for the update, you can try this.

https://shadcn-datetime-picker-xi.vercel.app/
https://github.com/huybuidac/shadcn-datetime-picker

**Comment by kamami** [comment]
Any update when the latest version of react-day-picker will be supported?

**Comment by kulterryan** [comment]
any update on this?

**Comment by olsio** [comment]
It will never get fixed. There are 850 open PRs with zero movement on maintenance. So you can only fix it for your own project and move on. I stopped contributing a while back. Nothing gets accepted.

**Comment by AnatoliiCubex** [comment]
Half a year and` 9.*.*` still messe styles of `8.**`

**Comment by junwen-k** [comment]
Hi everyone! 👋

I’m excited to share an extension library I’ve built for shadcn/ui, which includes a `DatePicker` reusable component. The calendar styling is updated and fixed, supporting `"react-day-picker": ^9`. It also supports additional features like [Dropdown Layout](https://ui-x.junwen-k.dev/docs/components/calendar#dropdown-layout).

You can check out the `DatePicker` component here: https://ui-x.junwen-k.dev/docs/components/date-picker

It also supports segmented date inputs using [timescape](https://github.com/dan-lee/timescape). 🚀 

The library also includes other handy components designed to enhance developer productivity. If you find it helpful, I’d be thrilled if you could leave a star—it really helps others discover the project. I’d love to hear your feedback or suggestions, so feel free to share your thoughts! 😊

**Comment by actraiser** [comment]
> You can check out the `DatePicker` component here: https://ui-x.junwen-k.dev/docs/components/date-picker

I cannot install the package with the command shown on the page

```
pnpm dlx cross-env REGISTRY_URL=https://ui-x.junwen-k.dev/r pnpm dlx shadcn@latest add date-picker

Something went wrong. Please check the error below for more details.
If the problem persists, please open an issue on GitHub.

Cannot read properties of undefined (reading 'resolvedPaths')
```

-act

**Comment by rylder** [comment]
I found something here: https://date-picker.luca-felix.com/
The guy did a beautiful job.
I hope it helps you too.

**Comment by huybuidac** [comment]
> I found something here: https://date-picker.luca-felix.com/ The guy did a beautiful job. I hope it helps you too.

Have you try this one https://shadcn-datetime-picker-pro.vercel.app?

**Comment by rylder** [comment]
> > I found something here: https://date-picker.luca-felix.com/ The guy did a beautiful job. I hope it helps you too.
> 
> Have you try this one https://shadcn-datetime-picker-pro.vercel.app?


I took a look, but I just needed the calendar styles corrected.
I already have my DatePicker component and just wanted to fix the style compatibility issue.
At another time, I will certainly test your component in my applications.

**Comment by tylerbecks** [comment]
> I found something here: https://date-picker.luca-felix.com/ The guy did a beautiful job. I hope it helps you too.

This is also the recommendation [in the docs](https://daypicker.dev/docs/styling).

**Comment by olsio** [comment]
I think we might get lucky and get an official fix as collateral. I think they are working on a tailwind 4 migration and will touch all the components.

**Comment by rahulcse1** [comment]
How long its going to take ? None of above solution are working.

**Comment by fekete965** [comment]
> How long its going to take ? None of above solution are working.

For now, I used his approach: https://date-picker.luca-felix.com/ 

Thanks you @rylder and @tylerbecks for the comments:
https://github.com/shadcn-ui/ui/issues/4366#issuecomment-2634864152
https://github.com/shadcn-ui/ui/issues/4366#issuecomment-2659984116

**Comment by kamami** [comment]
> > How long its going to take ? None of above solution are working.
> 
> For now, I used his approach: https://date-picker.luca-felix.com/
> 
> Thanks you [@rylder](https://github.com/rylder) and [@tylerbecks](https://github.com/tylerbecks) for the comments: [#4366 (comment)](https://github.com/shadcn-ui/ui/issues/4366#issuecomment-2634864152) [#4366 (comment)](https://github.com/shadcn-ui/ui/issues/4366#issuecomment-2659984116)

The year selection for the range input does not seem to be working.

**Comment by ha280** [comment]
`"use client";

import * as React from "react";
import { ChevronLeft, ChevronRight } from "lucide-react";
import { DayPicker } from "react-day-picker";

import { cn } from "@/lib/utils";

export type CalendarProps = React.ComponentProps<typeof DayPicker>;

function Calendar({
  className,
  classNames,
  showOutsideDays = true,
  ...props
}: CalendarProps) {
  return (
    <DayPicker
      showOutsideDays={showOutsideDays}
      className={cn("p-3", className)}
      classNames={{
        months: "flex flex-col sm:flex-row space-y-4 sm:space-y-0",
        month: "space-y-4 ",
        month_caption: "flex justify-center pt-1 relative items-center",
        caption_label: "text-sm font-medium",
        // nav: "space-x-1 flex items-center",
        button_next: cn(
          "inline-flex items-center justify-center gap-2 rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0 border border-input bg-background shadow-sm hover:bg-accent hover:text-accent-foreground h-9 px-4 py-2",
          "h-7 w-7 bg-transparent p-0 opacity-50 hover:opacity-100",
          "absolute right-5 z-50"
        ),
        button_previous: cn(
          "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0 border border-input bg-background shadow-sm hover:bg-accent hover:text-accent-foreground h-9 px-4 py-2",
          "h-7 w-7 bg-transparent p-0 opacity-50 hover:opacity-100",
          "absolute left-5 z-50"
        ),
        month_grid: "w-full border-collapse space-y-1",
        weekdays: "flex",
        weekday:
          "text-muted-foreground rounded-md w-8 font-normal text-[0.8rem]",
        week: "flex w-full mt-2",
        day: cn(
          "relative p-0 text-center text-sm focus-within:relative focus-within:z-20 [&:has([aria-selected])]:bg-accent [&:has([aria-selected].day-outside)]:bg-accent/50 [&:has([aria-selected].day-range-end)]:rounded-r-md",
          props.mode === "range"
            ? "[&:has(>.day-range-end)]:rounded-r-md [&:has(>.day-range-start)]:rounded-l-md first:[&:has([aria-selected])]:rounded-l-md last:[&:has([aria-selected])]:rounded-r-md"
            : "[&:has([aria-selected])]:rounded-md"
        ),
        day_button: cn(
          "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0 hover:bg-accent hover:text-accent-foreground",
          "h-8 w-8 p-0 font-normal aria-selected:opacity-100"
        ),
        range_start: "day-range-start",
        range_end: "day-range-end",
        selected:
          "bg-primary text-primary-foreground hover:bg-primary hover:text-primary-foreground focus:bg-primary focus:text-primary-foreground",
        today: "bg-accent text-accent-foreground",
        outside:
          "day-outside text-muted-foreground aria-selected:bg-accent/50 aria-selected:text-muted-foreground",
        disabled: "text-muted-foreground opacity-50",
        range_middle:
          "aria-selected:bg-accent aria-selected:text-accent-foreground",
        hidden: "invisible",
        ...classNames,
      }}
      components={{
        Chevron: (props) => {
          if (props.orientation === "left") {
            return (
              <ChevronLeft className={cn("h-4 w-4", className)} {...props} />
            );
          }
          return (
            <ChevronRight className={cn("h-4 w-4", className)} {...props} />
          );
        },
      }}
      {...props}
    />
  );
}
Calendar.displayName = "Calendar";

export { Calendar };
`

here is a code to fix the Calendar component

**Comment by daveycodez** [comment]
bing bong it's April 420 blaze it coming up

**Comment by rlawrence89** [comment]
> Here are my adjusted styles for the `Calendar` component: https://github.com/grzegorzpokorski/calendar-shadcnnui/blob/main/src/components/ui/calendar.tsx. Maybe someone will have more time to review them and improve.
> 
> The most intriguing aspect is the change in the structure of this component, particularly the navigation between months. I am not sure if the current design is appropriate (playing with `z-index`).

Thanks mate

**Comment by imjatinx** [comment]
> import * as React from "react"; import { ChevronLeft, ChevronRight } from "lucide-react"; import { DayPicker } from "react-day-picker";
> 
> import { cn } from "@/lib/utils";
> 
> export type CalendarProps = React.ComponentProps;
> 
> function Calendar({ className, classNames, showOutsideDays = true, ...props }: CalendarProps) { return ( <DayPicker showOutsideDays={showOutsideDays} className={cn("p-3", className)} classNames={{ months: "flex flex-col sm:flex-row space-y-4 sm:space-y-0", month: "space-y-4 ", month_caption: "flex justify-center pt-1 relative items-center", caption_label: "text-sm font-medium", // nav: "space-x-1 flex items-center", button_next: cn( "inline-flex items-center justify-center gap-2 rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0 border border-input bg-background shadow-sm hover:bg-accent hover:text-accent-foreground h-9 px-4 py-2", "h-7 w-7 bg-transparent p-0 opacity-50 hover:opacity-100", "absolute right-5 z-50" ), button_previous: cn( "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0 border border-input bg-background shadow-sm hover:bg-accent hover:text-accent-foreground h-9 px-4 py-2", "h-7 w-7 bg-transparent p-0 opacity-50 hover:opacity-100", "absolute left-5 z-50" ), month_grid: "w-full border-collapse space-y-1", weekdays: "flex", weekday: "text-muted-foreground rounded-md w-8 font-normal text-[0.8rem]", week: "flex w-full mt-2", day: cn( "relative p-0 text-center text-sm focus-within:relative focus-within:z-20 [&:has([aria-selected])]:bg-accent [&:has([aria-selected].day-outside)]:bg-accent/50 [&:has([aria-selected].day-range-end)]:rounded-r-md", props.mode === "range" ? "[&:has(>.day-range-end)]:rounded-r-md [&:has(>.day-range-start)]:rounded-l-md first:[&:has([aria-selected])]:rounded-l-md last:[&:has([aria-selected])]:rounded-r-md" : "[&:has([aria-selected])]:rounded-md" ), day_button: cn( "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0 hover:bg-accent hover:text-accent-foreground", "h-8 w-8 p-0 font-normal aria-selected:opacity-100" ), range_start: "day-range-start", range_end: "day-range-end", selected: "bg-primary text-primary-foreground hover:bg-primary hover:text-primary-foreground focus:bg-primary focus:text-primary-foreground", today: "bg-accent text-accent-foreground", outside: "day-outside text-muted-foreground aria-selected:bg-accent/50 aria-selected:text-muted-foreground", disabled: "text-muted-foreground opacity-50", range_middle: "aria-selected:bg-accent aria-selected:text-accent-foreground", hidden: "invisible", ...classNames, }} components={{ Chevron: (props) => { if (props.orientation === "left") { return ( <ChevronLeft className={cn("h-4 w-4", className)} {...props} /> ); } return ( <ChevronRight className={cn("h-4 w-4", className)} {...props} /> ); }, }} {...props} /> ); } Calendar.displayName = "Calendar";
> 
> export { Calendar };

Thank you bro, it works for me

**Comment by patrickcollins12** [comment]
I had this issue with react-day-picker after upgrading to 9.0.0.

After upgrading the calendar component it started working for me.

`npx shadcn@latest add calendar --overwrite`

Works!

**Comment by jkuri** [comment]
I managed to make styles work also for date range picker or multiple months with the current react-day-picker `v9.6.7`.

![Image](https://github.com/user-attachments/assets/bec48225-5efc-4d58-9274-3d1f1c8fdd00)

This is the code I use:

```ts
import { buttonVariants } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { ChevronLeft, ChevronRight } from "lucide-react";
import type { ComponentProps } from "react";
import { DayPicker } from "react-day-picker";

export type CalendarProps = ComponentProps<typeof DayPicker>;

function Calendar({ className, classNames, showOutsideDays = true, ...props }: CalendarProps) {
  return (
    <DayPicker
      showOutsideDays={showOutsideDays}
      className={cn("p-3", className)}
      classNames={{
        month: "space-y-4",
        months: "flex flex-col sm:flex-row space-y-4 sm:space-y-0 relative gap-2",
        month_caption: "flex justify-center pt-1 relative items-center",
        month_grid: "w-full border-collapse space-y-1",
        caption_label: "text-sm font-medium",
        nav: "flex items-center justify-between absolute inset-x-0",
        button_previous: cn(buttonVariants({ variant: "outline" }), "h-7 w-7 bg-transparent p-0 opacity-50 hover:opacity-100 z-10"),
        button_next: cn(buttonVariants({ variant: "outline" }), "h-7 w-7 bg-transparent p-0 opacity-50 hover:opacity-100 z-10"),
        weeks: "w-full border-collapse",
        weekdays: "flex",
        weekday: "text-muted-foreground rounded-md w-9 font-normal text-[0.8rem]",
        week: "flex w-full mt-2",
        day: "h-9 w-9 p-0 font-normal aria-selected:opacity-100 rounded-none first:aria-selected:rounded-l-md last:aria-selected:rounded-r-md",
        day_button: cn(
          buttonVariants({ variant: "ghost" }),
          "h-9 w-9 text-center text-sm p-0 relative focus-within:relative focus-within:z-20",
        ),
        range_start:
          "day-range-start !bg-accent rounded-l-md [&>button]:bg-primary [&>button]:text-primary-foreground [&>button]:hover:bg-primary [&>button]:hover:text-primary-foreground",
        range_end:
          "day-range-end !bg-accent rounded-r-md [&>button]:bg-primary [&>button]:text-primary-foreground [&>button]:hover:bg-primary [&>button]:hover:text-primary-foreground",
        range_middle: "aria-selected:bg-accent aria-selected:text-accent-foreground",
        day_selected:
          "bg-primary text-primary-foreground hover:bg-primary hover:text-primary-foreground focus:bg-primary focus:text-primary-foreground",
        day_today: "bg-accent text-accent-foreground",
        day_outside: "day-outside text-muted-foreground aria-selected:text-muted-foreground",
        day_disabled: "text-muted-foreground opacity-50",
        day_hidden: "invisible",
        selected:
          "bg-primary text-primary-foreground hover:bg-primary hover:text-primary-foreground focus:bg-primary focus:text-primary-foreground",
        today: "bg-accent text-accent-foreground",
        outside:
          "day-outside text-muted-foreground opacity-50 !aria-selected:bg-accent/50 !aria-selected:text-muted-foreground !aria-selected:opacity-30",
        disabled: "text-muted-foreground opacity-50",
        hidden: "invisible",
        ...classNames,
      }}
      components={{
        Chevron: ({ ...props }) =>
          props.orientation === "left" ? <ChevronLeft {...props} className="h-4 w-4" /> : <ChevronRight {...props} className="h-4 w-4" />,
      }}
      {...props}
    />
  );
}
Calendar.displayName = "Calendar";

export { Calendar };
```

**Comment by BramMeerten** [comment]
Thanks @jkuri ! I did some small tweaks to make it work for **both** range and single mode. And also I removed deprecated classes.

```diff
         range_end:
           "day-range-end !bg-accent rounded-r-md [&>button]:bg-primary [&>button]:text-primary-foreground [&>button]:hover:bg-primary [&>button]:hover:text-primary-foreground",
         range_middle: "aria-selected:bg-accent aria-selected:text-accent-foreground",
-        day_selected:
-          "bg-primary text-primary-foreground hover:bg-primary hover:text-primary-foreground focus:bg-primary focus:text-primary-foreground",
-        day_today: "bg-accent text-accent-foreground",
-        day_outside: "day-outside text-muted-foreground aria-selected:text-muted-foreground",
-        day_disabled: "text-muted-foreground opacity-50",
-        day_hidden: "invisible",
-        selected:
-          "bg-primary text-primary-foreground hover:bg-primary hover:text-primary-foreground focus:bg-primary focus:text-primary-foreground",
-        today: "bg-accent text-accent-foreground",
+        selected: cn(
+          props.mode === "range"
+            ? "bg-primary hover:bg-primary hover:text-primary-foreground focus:bg-primary focus:text-primary-foreground"
+            : "[&>button]:focus:bg-primary [&>button]:focus:text-primary-foreground",
+        ),
+        today: "bg-accent text-accent-foreground !rounded-md",
         outside:
           "day-outside text-muted-foreground opacity-50 !aria-selected:bg-accent/50 !aria-selected:text-muted-foreground !aria-selected:opacity-30",
         disabled: "text-muted-foreground opacity-50",
```

Complete file looks like this:
```ts
import { buttonVariants } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { ChevronLeft, ChevronRight } from "lucide-react";
import type { ComponentProps } from "react";
import { DayPicker } from "react-day-picker";

export type CalendarProps = ComponentProps<typeof DayPicker>;

function Calendar({ className, classNames, showOutsideDays = true, ...props }: CalendarProps) {
  return (
    <DayPicker
      showOutsideDays={showOutsideDays}
      className={cn("p-3", className)}
      classNames={{
        month: "space-y-4",
        months: "flex flex-col sm:flex-row space-y-4 sm:space-y-0 relative gap-2",
        month_caption: "flex justify-center pt-1 relative items-center",
        month_grid: "w-full border-collapse space-y-1",
        caption_label: "text-sm font-medium",
        nav: "flex items-center justify-between absolute inset-x-0",
        button_previous: cn(buttonVariants({ variant: "outline" }), "h-7 w-7 bg-transparent p-0 opacity-50 hover:opacity-100 z-10"),
        button_next: cn(buttonVariants({ variant: "outline" }), "h-7 w-7 bg-transparent p-0 opacity-50 hover:opacity-100 z-10"),
        weeks: "w-full border-collapse",
        weekdays: "flex",
        weekday: "text-muted-foreground rounded-md w-9 font-normal text-[0.8rem]",
        week: "flex w-full mt-2",
        day: "h-9 w-9 p-0 font-normal aria-selected:opacity-100 rounded-none first:aria-selected:rounded-l-md last:aria-selected:rounded-r-md",
        day_button: cn(
          buttonVariants({ variant: "ghost" }),
          "h-9 w-9 text-center text-sm p-0 relative focus-within:relative focus-within:z-20",
        ),
        range_start:
          "day-range-start !bg-accent rounded-l-md [&>button]:bg-primary [&>button]:text-primary-foreground [&>button]:hover:bg-primary [&>button]:hover:text-primary-foreground",
        range_end:
          "day-range-end !bg-accent rounded-r-md [&>button]:bg-primary [&>button]:text-primary-foreground [&>button]:hover:bg-primary [&>button]:hover:text-primary-foreground",
        range_middle: "aria-selected:bg-accent aria-selected:text-accent-foreground",
        selected: cn(
          props.mode === "range"
            ? "bg-primary hover:bg-primary hover:text-primary-foreground focus:bg-primary focus:text-primary-foreground"
            : "[&>button]:focus:bg-primary [&>button]:focus:text-primary-foreground",
        ),
        today: "bg-accent text-accent-foreground !rounded-md",
        outside:
          "day-outside text-muted-foreground opacity-50 !aria-selected:bg-accent/50 !aria-selected:text-muted-foreground !aria-selected:opacity-30",
        disabled: "text-muted-foreground opacity-50",
        hidden: "invisible",
        ...classNames,
      }}
      components={{
        Chevron: ({ ...props }) =>
          props.orientation === "left" ? <ChevronLeft {...props} className="h-4 w-4" /> : <ChevronRight {...props} className="h-4 w-4" />,
      }}
      {...props}
    />

  );
}
Calendar.displayName = "Calendar";

export { Calendar };
```

**Comment by jalvch10** [comment]
> Thanks [@jkuri](https://github.com/jkuri) ! I did some small tweaks to make it work for **both** range and single mode. And also I removed deprecated classes.
> 
>          range_end:
>            "day-range-end !bg-accent rounded-r-md [&>button]:bg-primary [&>button]:text-primary-foreground [&>button]:hover:bg-primary [&>button]:hover:text-primary-foreground",
>          range_middle: "aria-selected:bg-accent aria-selected:text-accent-foreground",
> -        day_selected:
> -          "bg-primary text-primary-foreground hover:bg-primary hover:text-primary-foreground focus:bg-primary focus:text-primary-foreground",
> -        day_today: "bg-accent text-accent-foreground",
> -        day_outside: "day-outside text-muted-foreground aria-selected:text-muted-foreground",
> -        day_disabled: "text-muted-foreground opacity-50",
> -        day_hidden: "invisible",
> -        selected:
> -          "bg-primary text-primary-foreground hover:bg-primary hover:text-primary-foreground focus:bg-primary focus:text-primary-foreground",
> -        today: "bg-accent text-accent-foreground",
> +        selected: cn(
> +          props.mode === "range"
> +            ? "bg-primary hover:bg-primary hover:text-primary-foreground focus:bg-primary focus:text-primary-foreground"
> +            : "[&>button]:focus:bg-primary [&>button]:focus:text-primary-foreground",
> +        ),
> +        today: "bg-accent text-accent-foreground !rounded-md",
>          outside:
>            "day-outside text-muted-foreground opacity-50 !aria-selected:bg-accent/50 !aria-selected:text-muted-foreground !aria-selected:opacity-30",
>          disabled: "text-muted-foreground opacity-50",
> Complete file looks like this:
> 
> import { buttonVariants } from "@/components/ui/button";
> import { cn } from "@/lib/utils";
> import { ChevronLeft, ChevronRight } from "lucide-react";
> import type { ComponentProps } from "react";
> import { DayPicker } from "react-day-picker";
> 
> export type CalendarProps = ComponentProps<typeof DayPicker>;
> 
> function Calendar({ className, classNames, showOutsideDays = true, ...props }: CalendarProps) {
>   return (
>     <DayPicker
>       showOutsideDays={showOutsideDays}
>       className={cn("p-3", className)}
>       classNames={{
>         month: "space-y-4",
>         months: "flex flex-col sm:flex-row space-y-4 sm:space-y-0 relative gap-2",
>         month_caption: "flex justify-center pt-1 relative items-center",
>         month_grid: "w-full border-collapse space-y-1",
>         caption_label: "text-sm font-medium",
>         nav: "flex items-center justify-between absolute inset-x-0",
>         button_previous: cn(buttonVariants({ variant: "outline" }), "h-7 w-7 bg-transparent p-0 opacity-50 hover:opacity-100 z-10"),
>         button_next: cn(buttonVariants({ variant: "outline" }), "h-7 w-7 bg-transparent p-0 opacity-50 hover:opacity-100 z-10"),
>         weeks: "w-full border-collapse",
>         weekdays: "flex",
>         weekday: "text-muted-foreground rounded-md w-9 font-normal text-[0.8rem]",
>         week: "flex w-full mt-2",
>         day: "h-9 w-9 p-0 font-normal aria-selected:opacity-100 rounded-none first:aria-selected:rounded-l-md last:aria-selected:rounded-r-md",
>         day_button: cn(
>           buttonVariants({ variant: "ghost" }),
>           "h-9 w-9 text-center text-sm p-0 relative focus-within:relative focus-within:z-20",
>         ),
>         range_start:
>           "day-range-start !bg-accent rounded-l-md [&>button]:bg-primary [&>button]:text-primary-foreground [&>button]:hover:bg-primary [&>button]:hover:text-primary-foreground",
>         range_end:
>           "day-range-end !bg-accent rounded-r-md [&>button]:bg-primary [&>button]:text-primary-foreground [&>button]:hover:bg-primary [&>button]:hover:text-primary-foreground",
>         range_middle: "aria-selected:bg-accent aria-selected:text-accent-foreground",
>         selected: cn(
>           props.mode === "range"
>             ? "bg-primary hover:bg-primary hover:text-primary-foreground focus:bg-primary focus:text-primary-foreground"
>             : "[&>button]:focus:bg-primary [&>button]:focus:text-primary-foreground",
>         ),
>         today: "bg-accent text-accent-foreground !rounded-md",
>         outside:
>           "day-outside text-muted-foreground opacity-50 !aria-selected:bg-accent/50 !aria-selected:text-muted-foreground !aria-selected:opacity-30",
>         disabled: "text-muted-foreground opacity-50",
>         hidden: "invisible",
>         ...classNames,
>       }}
>       components={{
>         Chevron: ({ ...props }) =>
>           props.orientation === "left" ? <ChevronLeft {...props} className="h-4 w-4" /> : <ChevronRight {...props} className="h-4 w-4" />,
>       }}
>       {...props}
>     />
> 
>   );
> }
> Calendar.displayName = "Calendar";
> 
> export { Calendar };



> Thanks [@jkuri](https://github.com/jkuri) ! I did some small tweaks to make it work for **both** range and single mode. And also I removed deprecated classes.
> 
>          range_end:
>            "day-range-end !bg-accent rounded-r-md [&>button]:bg-primary [&>button]:text-primary-foreground [&>button]:hover:bg-primary [&>button]:hover:text-primary-foreground",
>          range_middle: "aria-selected:bg-accent aria-selected:text-accent-foreground",
> -        day_selected:
> -          "bg-primary text-primary-foreground hover:bg-primary hover:text-primary-foreground focus:bg-primary focus:text-primary-foreground",
> -        day_today: "bg-accent text-accent-foreground",
> -        day_outside: "day-outside text-muted-foreground aria-selected:text-muted-foreground",
> -        day_disabled: "text-muted-foreground opacity-50",
> -        day_hidden: "invisible",
> -        selected:
> -          "bg-primary text-primary-foreground hover:bg-primary hover:text-primary-foreground focus:bg-primary focus:text-primary-foreground",
> -        today: "bg-accent text-accent-foreground",
> +        selected: cn(
> +          props.mode === "range"
> +            ? "bg-primary hover:bg-primary hover:text-primary-foreground focus:bg-primary focus:text-primary-foreground"
> +            : "[&>button]:focus:bg-primary [&>button]:focus:text-primary-foreground",
> +        ),
> +        today: "bg-accent text-accent-foreground !rounded-md",
>          outside:
>            "day-outside text-muted-foreground opacity-50 !aria-selected:bg-accent/50 !aria-selected:text-muted-foreground !aria-selected:opacity-30",
>          disabled: "text-muted-foreground opacity-50",
> Complete file looks like this:
> 
> import { buttonVariants } from "@/components/ui/button";
> import { cn } from "@/lib/utils";
> import { ChevronLeft, ChevronRight } from "lucide-react";
> import type { ComponentProps } from "react";
> import { DayPicker } from "react-day-picker";
> 
> export type CalendarProps = ComponentProps<typeof DayPicker>;
> 
> function Calendar({ className, classNames, showOutsideDays = true, ...props }: CalendarProps) {
>   return (
>     <DayPicker
>       showOutsideDays={showOutsideDays}
>       className={cn("p-3", className)}
>       classNames={{
>         month: "space-y-4",
>         months: "flex flex-col sm:flex-row space-y-4 sm:space-y-0 relative gap-2",
>         month_caption: "flex justify-center pt-1 relative items-center",
>         month_grid: "w-full border-collapse space-y-1",
>         caption_label: "text-sm font-medium",
>         nav: "flex items-center justify-between absolute inset-x-0",
>         button_previous: cn(buttonVariants({ variant: "outline" }), "h-7 w-7 bg-transparent p-0 opacity-50 hover:opacity-100 z-10"),
>         button_next: cn(buttonVariants({ variant: "outline" }), "h-7 w-7 bg-transparent p-0 opacity-50 hover:opacity-100 z-10"),
>         weeks: "w-full border-collapse",
>         weekdays: "flex",
>         weekday: "text-muted-foreground rounded-md w-9 font-normal text-[0.8rem]",
>         week: "flex w-full mt-2",
>         day: "h-9 w-9 p-0 font-normal aria-selected:opacity-100 rounded-none first:aria-selected:rounded-l-md last:aria-selected:rounded-r-md",
>         day_button: cn(
>           buttonVariants({ variant: "ghost" }),
>           "h-9 w-9 text-center text-sm p-0 relative focus-within:relative focus-within:z-20",
>         ),
>         range_start:
>           "day-range-start !bg-accent rounded-l-md [&>button]:bg-primary [&>button]:text-primary-foreground [&>button]:hover:bg-primary [&>button]:hover:text-primary-foreground",
>         range_end:
>           "day-range-end !bg-accent rounded-r-md [&>button]:bg-primary [&>button]:text-primary-foreground [&>button]:hover:bg-primary [&>button]:hover:text-primary-foreground",
>         range_middle: "aria-selected:bg-accent aria-selected:text-accent-foreground",
>         selected: cn(
>           props.mode === "range"
>             ? "bg-primary hover:bg-primary hover:text-primary-foreground focus:bg-primary focus:text-primary-foreground"
>             : "[&>button]:focus:bg-primary [&>button]:focus:text-primary-foreground",
>         ),
>         today: "bg-accent text-accent-foreground !rounded-md",
>         outside:
>           "day-outside text-muted-foreground opacity-50 !aria-selected:bg-accent/50 !aria-selected:text-muted-foreground !aria-selected:opacity-30",
>         disabled: "text-muted-foreground opacity-50",
>         hidden: "invisible",
>         ...classNames,
>       }}
>       components={{
>         Chevron: ({ ...props }) =>
>           props.orientation === "left" ? <ChevronLeft {...props} className="h-4 w-4" /> : <ChevronRight {...props} className="h-4 w-4" />,
>       }}
>       {...props}
>     />
> 
>   );
> }
> Calendar.displayName = "Calendar";
> 
> export { Calendar };

worked for me

**Comment by vonner04** [comment]
> I managed to make styles work also for date range picker or multiple months with the current react-day-picker `v9.6.7`.
> 
> ![Image](https://github.com/user-attachments/assets/bec48225-5efc-4d58-9274-3d1f1c8fdd00)
> 
> This is the code I use:
> 
> import { buttonVariants } from "@/components/ui/button";
> import { cn } from "@/lib/utils";
> import { ChevronLeft, ChevronRight } from "lucide-react";
> import type { ComponentProps } from "react";
> import { DayPicker } from "react-day-picker";
> 
> export type CalendarProps = ComponentProps<typeof DayPicker>;
> 
> function Calendar({ className, classNames, showOutsideDays = true, ...props }: CalendarProps) {
>   return (
>     <DayPicker
>       showOutsideDays={showOutsideDays}
>       className={cn("p-3", className)}
>       classNames={{
>         month: "space-y-4",
>         months: "flex flex-col sm:flex-row space-y-4 sm:space-y-0 relative gap-2",
>         month_caption: "flex justify-center pt-1 relative items-center",
>         month_grid: "w-full border-collapse space-y-1",
>         caption_label: "text-sm font-medium",
>         nav: "flex items-center justify-between absolute inset-x-0",
>         button_previous: cn(buttonVariants({ variant: "outline" }), "h-7 w-7 bg-transparent p-0 opacity-50 hover:opacity-100 z-10"),
>         button_next: cn(buttonVariants({ variant: "outline" }), "h-7 w-7 bg-transparent p-0 opacity-50 hover:opacity-100 z-10"),
>         weeks: "w-full border-collapse",
>         weekdays: "flex",
>         weekday: "text-muted-foreground rounded-md w-9 font-normal text-[0.8rem]",
>         week: "flex w-full mt-2",
>         day: "h-9 w-9 p-0 font-normal aria-selected:opacity-100 rounded-none first:aria-selected:rounded-l-md last:aria-selected:rounded-r-md",
>         day_button: cn(
>           buttonVariants({ variant: "ghost" }),
>           "h-9 w-9 text-center text-sm p-0 relative focus-within:relative focus-within:z-20",
>         ),
>         range_start:
>           "day-range-start !bg-accent rounded-l-md [&>button]:bg-primary [&>button]:text-primary-foreground [&>button]:hover:bg-primary [&>button]:hover:text-primary-foreground",
>         range_end:
>           "day-range-end !bg-accent rounded-r-md [&>button]:bg-primary [&>button]:text-primary-foreground [&>button]:hover:bg-primary [&>button]:hover:text-primary-foreground",
>         range_middle: "aria-selected:bg-accent aria-selected:text-accent-foreground",
>         day_selected:
>           "bg-primary text-primary-foreground hover:bg-primary hover:text-primary-foreground focus:bg-primary focus:text-primary-foreground",
>         day_today: "bg-accent text-accent-foreground",
>         day_outside: "day-outside text-muted-foreground aria-selected:text-muted-foreground",
>         day_disabled: "text-muted-foreground opacity-50",
>         day_hidden: "invisible",
>         selected:
>           "bg-primary text-primary-foreground hover:bg-primary hover:text-primary-foreground focus:bg-primary focus:text-primary-foreground",
>         today: "bg-accent text-accent-foreground",
>         outside:
>           "day-outside text-muted-foreground opacity-50 !aria-selected:bg-accent/50 !aria-selected:text-muted-foreground !aria-selected:opacity-30",
>         disabled: "text-muted-foreground opacity-50",
>         hidden: "invisible",
>         ...classNames,
>       }}
>       components={{
>         Chevron: ({ ...props }) =>
>           props.orientation === "left" ? <ChevronLeft {...props} className="h-4 w-4" /> : <ChevronRight {...props} className="h-4 w-4" />,
>       }}
>       {...props}
>     />
>   );
> }
> Calendar.displayName = "Calendar";
> 
> export { Calendar };

Just curious how were you able to figure out how to change the styles?

**Comment by jkuri** [comment]
> > I managed to make styles work also for date range picker or multiple months with the current react-day-picker `v9.6.7`.
> > ![Image](https://github.com/user-attachments/assets/bec48225-5efc-4d58-9274-3d1f1c8fdd00)
> > This is the code I use:
> 
> Just curious how were you able to figure out how to change the styles? [@jkuri](https://github.com/jkuri)

@vonner04 I checked the source of the `react-day-picker` latest version.

**Comment by luchillo17** [comment]
I can't downgrade, I would be forced to downgrade `date-fns` as well...

**Comment by daveycodez** [comment]
What's the ETA here?

**Comment by sscotth** [comment]
Should be fixed now

https://github.com/shadcn-ui/ui/pull/7551

https://ui.shadcn.com/docs/components/calendar#upgrade-guide

**Comment by peturgeorgievv** [comment]
> Should be fixed now
> 
> [#7551](https://github.com/shadcn-ui/ui/pull/7551)
> 
> https://ui.shadcn.com/docs/components/calendar#upgrade-guide

Still doesn't work properly in terms of styling, or at least it doesn't look like in the docs.

**Comment by fers4t** [comment]
> 9.6.7

thanks!

**Comment by fers4t** [comment]
https://github.com/shadcn-ui/ui/issues/4366#issuecomment-2818418140
thanks

**Comment by BramMeerten** [comment]
> Should be fixed now
> 
> [#7551](https://github.com/shadcn-ui/ui/pull/7551)
> 
> https://ui.shadcn.com/docs/components/calendar#upgrade-guide

This fixed it for me.
@peturgeorgievv what part of the styling is still broken for you?

**Comment by connorjchen** [comment]
fyi, i was struggling with installing the new shadcn calendar component, but realized i was still on tailwind v3, so i needed a separate version

https://ui.shadcn.com/docs/components/calendar#tailwind-v3

**Comment by mrbeandev** [comment]
for me i had to downgrade my `react` to `18` and `react-day-picker` to `9.0.0` , and now if you use `npm install` it would still give another issue , so i had to start using `pnpm install` which has finally fixed the issue ,and now its perfect ! 

and u might sometimes get some issues with `date-fns` so just uninstall it and try to reinstall the `react-day-picker@9.0.0` again 

and also used this calender component code:
```tsx
"use client";

import * as React from "react";
import { ChevronLeft, ChevronRight } from "lucide-react";
import { DayPicker } from "react-day-picker";

import { cn } from "@/lib/utils";
import { buttonVariants } from "@/components/ui/button";

export type CalendarProps = React.ComponentProps<typeof DayPicker>;

function Calendar({ className, classNames, showOutsideDays = true, ...props }: CalendarProps) {
	return (
		<DayPicker
			showOutsideDays={showOutsideDays}
			className={cn("p-3", className)}
			classNames={{
				month: "space-y-4",
				months: "flex flex-col sm:flex-row space-y-4 sm:space-y-0 relative",
				month_caption: "flex justify-center pt-1 relative items-center",
				month_grid: "w-full border-collapse space-y-1",
				caption_label: "text-sm font-medium",
				nav: "flex items-center justify-between absolute inset-x-0",
				button_previous: cn(buttonVariants({ variant: "outline" }), "h-7 w-7 bg-transparent p-0 opacity-50 hover:opacity-100 z-10"),
				button_next: cn(buttonVariants({ variant: "outline" }), "h-7 w-7 bg-transparent p-0 opacity-50 hover:opacity-100 z-10"),
				weeks: "w-full border-collapse space-y-",
				weekdays: "flex",
				weekday: "text-muted-foreground rounded-md w-9 font-normal text-[0.8rem]",
				week: "flex w-full mt-2",
				day_button: "h-9 w-9 text-center text-sm p-0 relative [&:has([aria-selected].day-range-end)]:rounded-r-md [&:has([aria-selected].day-outside)]:bg-accent/50 [&:has([aria-selected])]:bg-accent first:[&:has([aria-selected])]:rounded-l-md last:[&:has([aria-selected])]:rounded-r-md focus-within:relative focus-within:z-20",
				day: cn(buttonVariants({ variant: "ghost" }), "h-9 w-9 p-0 font-normal aria-selected:opacity-100"),
				range_end: "day-range-end rounded-l-none",
				range_start: "day-range-start rounded-r-none",
				selected: "bg-primary text-primary-foreground hover:bg-primary hover:text-primary-foreground focus:bg-primary focus:text-primary-foreground",
				today: "bg-accent text-accent-foreground",
				outside: "day-outside text-muted-foreground opacity-50 aria-selected:bg-accent/50 aria-selected:text-muted-foreground aria-selected:opacity-30",
				disabled: "text-muted-foreground opacity-50",
				range_middle: "aria-selected:bg-accent rounded-none aria-selected:text-accent-foreground",
				hidden: "invisible",
				...classNames,
			}}
			components={{
				Chevron: ({ ...props }) => (props.orientation === "left" ? <ChevronLeft {...props} className="h-4 w-4" /> : <ChevronRight {...props} className="h-4 w-4" />),
			}}
			{...props}
		/>
	);
}
Calendar.displayName = "Calendar";

export { Calendar };
```

Result:
<img width="541" height="412" alt="Image" src="https://github.com/user-attachments/assets/a8d4c220-ee89-46b4-b59d-7aeb96d3cc36" />


Thank to for sharing the codes : https://github.com/grzegorzpokorski/calendar-shadcnnui

<details>
<summary>
my package.json content
</summary>

```json
{
	"name": "frontend",
	"private": true,
	"version": "0.0.0",
	"type": "module",
	"scripts": {
		"dev": "vite",
		"build": "tsc -b && vite build",
		"lint": "eslint .",
		"preview": "vite preview"
	},
	"dependencies": {
		"@radix-ui/react-alert-dialog": "^1.1.15",
		"@radix-ui/react-avatar": "^1.1.11",
		"@radix-ui/react-checkbox": "^1.3.3",
		"@radix-ui/react-dialog": "^1.1.15",
		"@radix-ui/react-dropdown-menu": "^2.1.16",
		"@radix-ui/react-label": "^2.1.8",
		"@radix-ui/react-popover": "^1.1.15",
		"@radix-ui/react-select": "^2.2.6",
		"@radix-ui/react-slot": "^1.2.4",
		"@radix-ui/react-switch": "^1.2.6",
		"@radix-ui/react-tabs": "^1.1.13",
		"@tabler/icons-react": "^3.35.0",
		"@tailwindcss/vite": "^4.1.17",
		"@tanstack/react-table": "^8.21.3",
		"autoprefixer": "^10.4.22",
		"axios": "^1.13.2",
		"class-variance-authority": "^0.7.1",
		"clsx": "^2.1.1",
		"cmdk": "^1.1.1",
		"framer-motion": "^12.23.24",
		"highcharts": "^12.4.0",
		"highcharts-react-official": "^3.2.3",
		"lucide-react": "^0.554.0",
		"motion": "^12.23.24",
		"next-themes": "^0.4.6",
		"react-day-picker": "^9.0.0",
		"react": "^18.3.1",
		"react-dom": "^18.3.1",
		"react-router-dom": "^7.9.6",
		"sonner": "^2.0.7",
		"tailwind-merge": "^3.4.0",
		"tailwindcss": "^4.1.17",
		"tailwindcss-animate": "^1.0.7",
		"tw-animate-css": "^1.4.0"
	},
	"devDependencies": {
		"@eslint/js": "^9.39.1",
		"@types/node": "^24.10.1",
		"@types/react": "^18.3.3",
		"@types/react-dom": "^18.3.0",
		"@vitejs/plugin-react": "^5.1.0",
		"eslint": "^9.39.1",
		"eslint-plugin-react-hooks": "^7.0.1",
		"eslint-plugin-react-refresh": "^0.4.24",
		"globals": "^16.5.0",
		"typescript": "~5.9.3",
		"typescript-eslint": "^8.46.3",
		"vite": "^7.2.2"
	}
}
```
</ details>
