### ISSUE TITLE
[bug]: npx shadcn@latest add toast creating hooks folder outside components

### ISSUE THREAD

**Issue by ronijaat** [shadcn-ui/ui#4828]
### Describe the bug

PS C:\Users\HP\Desktop\office\package-maker> npx shadcn@latest add toast
Need to install the following packages:
shadcn@2.0.6
Ok to proceed? (y) y

✔ Checking registry.
✔ Installing dependencies.
✔ Created 3 files:
  - components\ui\toast.tsx
  - hooks\use-toast.ts
  - components\ui\toaster.tsx
  - ----------------------------------------
  Failed to compile

Next.js (14.2.5) out of date [(learn more)](https://nextjs.org/docs/messages/version-staleness)
./components/ui/toaster.tsx:3:1
Module not found: Can't resolve '@/components/hooks/use-toast'
  1 | "use client"
  2 |
> 3 | import { useToast } from "@/components/hooks/use-toast"
    | ^
  4 | import {
  5 |   Toast,
  6 |   ToastClose,

https://nextjs.org/docs/messages/module-not-found

### Affected component/components

Toast

### How to reproduce

1. npx shadcn@latest add toast

### Codesandbox/StackBlitz link

yes

### Logs

```bash
no
```

### System Info

```bash
windows 11
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by jmfp** [comment]
Same problem on mac

**Comment by mellolauro** [comment]
Problem win 11 .  node -v  -- > v20.17.0
npm -v --> 10.8.2

npx shadcn@latest init
✔ Preflight checks.
✔ Verifying framework. Found Next.js.
✔ Validating Tailwind CSS.
✔ Validating import alias.


Something went wrong. Please check the error below for more details.
If the problem persists, please open an issue on GitHub.

request to https://ui.shadcn.com/r/styles/index.json failed, reason: self-signed certificate in certificate chain

**Comment by bretzke** [comment]
I have the same problem.

**Comment by ericjy** [comment]
### Solution
This solution works for me. Modify the newly added `components/ui/toaster.tsx` file:

Change 

```typescript
import { useToast } from "@/components/hooks/use-toast";
```
to

```typescript
import { useToast } from "@/hooks/use-toast";
```

This is because the `use-toast.tsx` is added to the `hooks` dir,  not `components/hooks` dir.

Or you can move the `use-toast.tsx` to `components/hooks`

**Comment by suprunchuk** [comment]
**THE PROBLEM IS SOLVED!!!**

I have exactly the same problem.
![image](https://github.com/user-attachments/assets/e04c1fdd-aa16-4d6f-ad98-d22ca4cb2e10)

Replace the current line:
```ts
import { toast } from "@/components/hooks/use-toast";
```

On this line:
```ts
import { toast } from "@/hooks/use-toast";
```

![image](https://github.com/user-attachments/assets/49d5e185-6dc4-4346-9f8c-f00100a2a86b)

**Comment by mschilde** [comment]
The issue is not fixed, but can be handled manually quickly.

**Comment by malo-dev** [comment]
"Replace the line `import { toast } from "@/components/hooks/use-toast" `![Uploading Screenshot from 2024-11-09 08-40-45.png…]() with` import { toast } from "@/components/hooks/use-toast".`
![Screenshot from 2024-11-09 08-40-42](https://github.com/user-attachments/assets/b4dc026c-a67e-4763-a118-422aaf03b2a4)

**Comment by sarru1291** [comment]
The problem is still not resolved by default.

**Comment by wpenistone** [comment]
still not fixed
