### ISSUE TITLE
[bug]: Components installed to wrong directory Remix

### ISSUE THREAD

**Issue by pjosxyz** [shadcn-ui/ui#5436]
### Describe the bug

Components not being installed to location defined in component.json. Instead a components folder in the root directory is being created.

**components.json**
```json
  "aliases": {
    "components": "~/components",
    "utils": "~/lib/utils",
    "ui": "~/components/ui",
    "lib": "~/lib",
    "hooks": "~/hooks"
  }
```

**tsconfig.json**
```json
    "baseUrl": ".",
    "paths": {
      "~/*": ["./app/*"]
    },
```

### Affected component/components

All

### How to reproduce

Followed steps described here https://ui.shadcn.com/docs/installation/remix

### Codesandbox/StackBlitz link

https://stackblitz.com/edit/remix-run-remix-c99tma?file=tailwind.config.ts

### System Info

```bash
ProductName:		macOS
ProductVersion:		14.6.1
BuildVersion:		23G9
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by mjjabarullah** [comment]
The same issue for me when adding components. It should be added inside app folder instead components added in root folder

**Comment by sadbytes** [comment]
Facing the same issue in Laravel, it should be installed in `./resouces/js/components/ui ` but instead it's installing in `./components/ui/`. 

tsconfig.json
```
"baseUrl": ".",
"paths": {
    "@/*": ["./resources/js/*"],
    "@images/*": ["./resources/images/*"],
    "ziggy-js": ["./vendor/tightenco/ziggy"]
}
```

components.json
```
"aliases": {
    "components": "@/components",
    "utils": "@/lib/utils",
    "ui": "@/components/ui",
    "lib": "@/lib",
    "hooks": "@/hooks"
  }
  ```

**Comment by omsrg** [comment]
having the same issue with remix

**Comment by muhammadaldan** [comment]
having same issue with laravel ,I've tried making a new project, but the new init still doesn't work, I think this is related to the sidebar update? Yesterday it was still okay

**Comment by shavonn** [comment]
Same same

**Comment by vaneworks** [comment]
Same issue, but for Vite project (TanStack Start). The hooks directory is also getting installed to the root folder.

**Comment by jacobtipp** [comment]
Same issue in my nextjs app, it worked fine a few weeks ago and I've made no changes to my config.

components should be added to `./src/shared/components/` but instead are added to `./src/components/`

```jsonc
// components.json
{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "default",
  "rsc": true,
  "tsx": true,
  "tailwind": {
    "config": "tailwind.config.ts",
    "css": "src/app/globals.css",
    "baseColor": "zinc",
    "cssVariables": true,
    "prefix": ""
  },
  "aliases": {
    "components": "@/shared/components",
    "utils": "@/shared/utils"
  }
}
```

```jsonc
//tsconfig.json
{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "noImplicitAny": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "noImplicitReturns": false,
    "noImplicitOverride": true,
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    ".next/types/**/*.ts",
    "src/lib/server/error-handlers"
  ],
  "exclude": ["node_modules"]
}
```

**Comment by MaximePremont** [comment]
Hello, I'm having the same issue with Next too.
```
// tsconfig.json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "incremental": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "paths": {
      "@/*": ["./renderer/*"]
    },
    "plugins": [
      {
        "name": "next"
      }
    ]
  },
  "exclude": ["node_modules", "renderer/next.config.js", "app", "dist"],
  "include": ["next-env.d.ts", ".next/types/**/*.ts", "**/*.ts", "**/*.tsx"]
}
```

```
// components.json
{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "default",
  "rsc": true,
  "tsx": true,
  "tailwind": {
    "config": "@/tailwind.config.js",
    "css": "@/styles/globals.css",
    "baseColor": "slate",
    "cssVariables": true,
    "prefix": ""
  },
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils"
  }
}
```

**Comment by lucasfeliciano** [comment]
See the following comment for more info about the bug:
https://github.com/shadcn-ui/ui/issues/5433#issuecomment-2425131609

**Comment by bakikucukcakiroglu** [comment]
Yes, I'm facing the same issue. It was working well 1 week ago, I didin't change anything. [Remix]

**Comment by VerioN1** [comment]
me too

**Comment by shmuli9** [comment]
Urgh, this sucked up 2 hours of my life...
Same issue and cant seem to find a fix

Using shadcn-ui@0.8.0 works as expected though

(in my case I have aliases for my main app: `"~/*": ["./app/*"]`, and `"@/*": ["./app/shadcn/*"]`)

**Comment by shmuli9** [comment]
Not sure, but wondering whether another issue I am running into is related?

If i set my tsconfig like so:

```
"paths": {
  "@/*": ["./app/shadcn/*"]
},
```

and run `npx shadcn@latest init`, I get this error:

```
✔ Preflight checks.
✔ Verifying framework. Found Vite.
✔ Validating Tailwind CSS.
✖ Validating import alias.

No import alias found in your tsconfig.json file.
Visit https://ui.shadcn.com/docs/installation/vite to learn how to set an import alias.
```

**Comment by natemking** [comment]
Can confirm that I too am seeing what @shmuli9 is seeing. Everything worked fine a few weeks ago until attempting to install new components today. I trying re-running an intit and I an seeing the same `✖ Validating import alias.`  error.

**Comment by trulysinclair** [comment]
Wasted an hour on this thinking it was a user error lol, AdonisJS + Intertia + React + ShadCN/UI. Actually, exactly the same setup as https://github.com/johnpgr/adonisjs-inertia-react-shadcnui which I just found. Previously it worked, new CLI now isn't working. Was about to shoot my PC haha

**Comment by BrendanRomanDev** [comment]
A needless but important +1 to this issue. Just wasted an hour and a half troubleshooting thinking I was the issue! Glad I'm not crazy.

**Comment by sukronsabari** [comment]
+1 same issue

**Comment by jezao** [comment]
+1

**Comment by shadcn** [comment]
I pushed a fix for it. Can we confirm if it's working now? (also let's track in #5433)

**Comment by shmuli9** [comment]
This is working partly, but still not behaving as I would expect.

When I set my tsconfig like so:
```
    "paths": {
      "~/*": ["./app/*"]
    },
```

shadcn installs "correctly" to `app/["lib"/"components"/"hooks"]`, but I am trying to set a custom directory for shadcn components like so:

```
    "paths": {
      "@/*": ["./app/shadcn/*"]
    },
```

this fails with the following error:

```
npx shadcn@latest init
✔ Preflight checks.
✔ Verifying framework. Found Vite.
✔ Validating Tailwind CSS.
✖ Validating import alias.

No import alias found in your tsconfig.json file.
Visit https://ui.shadcn.com/docs/installation/vite to learn how to set an import alias.
```

In previous CLI you could set a custom import alias, but for some reason in v2 this doesnt work as expected. It seems like only ~/ is supported as a custom import

**Comment by omsrg** [comment]
it's working perfectly now

**Comment by shadcn** [comment]
@shmuli9 You can do this in your `components.json` file:

```json
"aliases": {
  "components": "@/shadcn",
  "ui": "@/shadcn/ui",
}
```

This will put all components in `./shadcn` and ui in `./shadcn/ui`

**Comment by shmuli9** [comment]
> @shmuli9 You can do this in your `components.json` file:
> 
> 
> 
> ```json
> 
> "aliases": {
> 
>   "components": "@/shadcn",
> 
>   "ui": "@/shadcn/ui",
> 
> }
> 
> ```
> 
> 
> 
> This will put all components in `./shadcn` and ui in `./shadcn/ui`

Oh, you mean after init, modify the components.json? That occurred to me, but wasn't sure why the old behaviour wasn't working

I think there is still an issue because `init` doesn't accept the "@/*" path as a valid alias. 

But for now your suggestion should be a good enough workaround for me. Thanks @shadcn

**Comment by pjosxyz** [comment]
> I pushed a fix for it. Can we confirm if it's working now? (also let's track in #5433)

Can confirm components are being installed to the correct directory (as specified in components.json and tsconfig /app/components/) in Remix 

Thanks a million!
