### ISSUE TITLE
[bug]: Popover Content not working within the use of Dialog Content

### ISSUE THREAD

**Issue by kaustubh2525** [shadcn-ui/ui#6106]
### Describe the bug

1) I have an issue where i have a link which has longer text and i needed to open them separately in dialog and showing them.
2) Now when i added Popover and all of its related components with className of (truncate) on PopoverTrigger such that when i click on that truncated line the Popover opens and i can select and copy the whole link from there but, now the issue is that i can't click on any content on the Popover Content.

![dialog and popover mixture issue](https://github.com/user-attachments/assets/507cdaf8-e130-4a8b-9768-56274b55d402)

### Affected component/components

PopoverContent

### How to reproduce

<Dialog>
   <DialogTrigger>Some</DialogTrigger>
   <DialogContent>
    <Popover modal>
          <PopoverTrigger className="w-40 truncate hover:text-muted-foreground/90">
             // Supposed to be link that is truncated
            lorem50 can be used for demo
          </PopoverTrigger>
          <PopoverContent align="start">
             // Supposed to be the whole link
            lorem50 can be used for demo
          </PopoverContent>
        </Popover>
   </DialogContent>
</Dialog

### System Info

```bash
Google Chrome -> Version 131.0.6778.140
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by kmhalvin** [comment]
This bug also occurred in my app, fixed it by updating these dependencies to the latest version.

"@radix-ui/react-dialog": "^1.1.4",
"@radix-ui/react-popover": "^1.1.4",

**Comment by 54sword** [comment]
I encountered the same issue, and then I updated all of radix-ui/*, and it started working properly.

**Comment by 54sword** [comment]
I encountered the same issue, and then I updated all of radix-ui/*, and it started working properly.

**Comment by kaustubh2525** [comment]
@kmhalvin @54sword Thanks for the feedback, it indeed corrected that bug that caused! My issue has been resolved but i am just curious why did that occured in the first place if anyone can explain in short that would be helpful.

**Comment by KingAlastor** [comment]
i updated all my radix-ui packages but i still can't interact with the popover contents within a dialog/drawer component. Does anyone know what was the fix i could look for? 
I'm currently at:
"@radix-ui/react-dialog": "^1.1.4",
"@radix-ui/react-popover": "^1.1.4",

**Comment by kaustubh2525** [comment]
@KingAlastor don't know what fixed it but the version bump did the job right now, but again same curious what was that fix if they did any then ?

**Comment by KingAlastor** [comment]
@kaustubh2525 i deleted node_modules and re-installed everything and got it to work now as well.

**Comment by demonfiddler** [comment]
Same issue here, updating @radix-ui/react-popover from 1.1.6 to 1.1.15 fixed the problem (@radix-ui/react-dialog stayed at latest, 1.1.15).
