### ISSUE TITLE
[bug]:  animation behavior for the Dialog component

### ISSUE THREAD

**Issue by mo1nammad** [shadcn-ui/ui#6649]
### **The default animation behavior for the DialogContent component does not match the preview shown on the ShadCN UI website. The transition effect when opening and closing the dialog feels unnatural and creates an unpleasant user experience.**

he following classnames are causing the unexpected animation behavior:
```
data-[state=closed]:slide-out-to-left-1/2 
data-[state=closed]:slide-out-to-top-[48%] 
data-[state=open]:slide-in-from-left-1/2 
data-[state=open]:slide-in-from-top-[48%]
```

- When the dialog opens, it slides in diagonally from the left and top, which feels jarring.
- When closing, it moves diagonally in the opposite direction, making the animation look unnatural.
- This behavior is inconsistent with the smooth, centered zoom-in/zoom-out effect shown in the preview.

I was able to fix this by removing the problematic classes and only keeping the zoom and fade animations:

Environment
Tailwindcss : 4.0.6
tailwindcss-animate: "^1.0.7",
tailwindcss: "^4.0.6",
ShadCN UI latest version
React :19

### Affected component/components

Dialog

### How to reproduce

Use the default Dialog component from ShadCN UI.
Open and close the dialog multiple times.
Notice the unexpected diagonal sliding effect.

### Logs

```bash

```

### System Info

```bash
Linux
```

### Before submitting

- [x] I've made research efforts and searched the documentation
- [x] I've searched for existing issues

**Comment by dinkopehar** [comment]
Happens to me also while working. On https://ui.shadcn.com/docs/components/dialog it does not happen, copying the example (_Custom Close Button)_ it slides from left top and slides back on pressing X.

**Comment by eposha** [comment]
The same issue

**Comment by Pety99** [comment]
Removing the classes fixed it for me too. Thanks!

**Comment by Heher** [comment]
Just a heads up for anyone following this. I had originally manually copied the code for the Dialog using the "Manual" tab in the Installation section. I just used the CLI and copied the code it installed into my existing Dialog.tsx and it works normally now.

**Comment by cabello** [comment]
Ditto! I did not have this issue on tailwind v3, it showed up just after upgrading to v4. Removing the slide outs and in fixed the dialog, instead of sliding from the top-left down to the center, it just shows up by fading in.

**Comment by Naufal05R** [comment]
Resolved issue for me. Try to add these classNames to the DialogContent component:

```
data-[state=open]:animate-in 
data-[state=closed]:animate-out
```

along with

```
data-[state=closed]:slide-out-to-left-1/2 
data-[state=closed]:slide-out-to-top-[48%] 
data-[state=open]:slide-in-from-left-1/2 
data-[state=open]:slide-in-from-top-[48%]
```

Animation behavior should work well and look very nice.

**Comment by kein-1** [comment]
> Ditto! I did not have this issue on tailwind v3, it showed up just after upgrading to v4. Removing the slide outs and in fixed the dialog, instead of sliding from the top-left down to the center, it just shows up by fading in.

This solved it for me too; I removed the slide-in classes inside DialogContent

**Comment by nirajrajgor** [comment]
This still happens if you install the component via command `npx shadcn@latest add dialog`. Just remove the classes if you don't need the animation from top right.

**Comment by jordihoven** [comment]
For anyone using Shadcn-vue, removing:

```
data-[state=closed]:slide-out-to-left-1/2 
data-[state=closed]:slide-out-to-top-[48%] 
data-[state=open]:slide-in-from-left-1/2 
data-[state=open]:slide-in-from-top-[48%]
```


from the `DialogContent.vue` file solves this issue.

**Comment by shubhamtak007** [comment]
Remove these classes (animate-in,out and fade-in-0, fade-out-0)  from dialog component, and replace with offical tailwind class. these classes (animate-in,out and fade-in-0, fade-out-0) are from tailwind animate which is not support in v4.

I have done this in my project 

https://github.com/shubhamtak007/coinova/blob/main/app/globals.scss
https://github.com/shubhamtak007/coinova/blob/main/components/ui/dialog.tsx
