### ISSUE TITLE
[bug]: forwardRef() missing for some components

### ISSUE THREAD

**Issue by Sladerix** [shadcn-ui/ui#7229]
I noticed that using some components I get this error in console
```
[Error] Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `Primitive.button.SlotClone`.
Button@http://localhost:5173/src/components/ui/button.jsx:47:12
Primitive.button.SlotClone@http://localhost:5173/node_modules/.vite/deps/chunk-MT2JQ6XZ.js:79:45
Primitive.button.Slot@http://localhost:5173/node_modules/.vite/deps/chunk-MT2JQ6XZ.js:56:45
Primitive.button@http://localhost:5173/node_modules/.vite/deps/@radix-ui_react-popover.js:142:49
Primitive.div.SlotClone@http://localhost:5173/node_modules/.vite/deps/chunk-MT2JQ6XZ.js:79:45
Primitive.div.Slot@http://localhost:5173/node_modules/.vite/deps/chunk-MT2JQ6XZ.js:56:45
Primitive.div@http://localhost:5173/node_modules/.vite/deps/@radix-ui_react-popover.js:142:49
PopperAnchor@http://localhost:5173/node_modules/.vite/deps/@radix-ui_react-popover.js:623:64
PopoverTrigger@http://localhost:5173/node_modules/.vite/deps/@radix-ui_react-popover.js:1026:54
PopoverTrigger@http://localhost:5173/src/components/ui/popover.jsx:30:25
PopoverProvider@http://localhost:5173/node_modules/.vite/deps/@radix-ui_react-popover.js:61:52
PopperProvider@http://localhost:5173/node_modules/.vite/deps/@radix-ui_react-popover.js:61:52
Popper@http://localhost:5173/node_modules/.vite/deps/@radix-ui_react-popover.js:615:44
Popover@http://localhost:5173/node_modules/.vite/deps/@radix-ui_react-popover.js:980:12
Popover@http://localhost:5173/src/components/ui/popover.jsx:20:18
div
DateRanges@http://localhost:5173/src/components/DateRanges.jsx:82:27
form
div
div
div
BillboardForm@http://localhost:5173/src/pages/BillboardForm.jsx:30:27
RenderedRoute@http://localhost:5173/node_modules/.vite/deps/react-router.js:5370:38
Routes@http://localhost:5173/node_modules/.vite/deps/react-router.js:6100:11
App@http://localhost:5173/src/App.jsx:44:51
Provider@http://localhost:5173/node_modules/.vite/deps/react-redux.js:923:66
Router@http://localhost:5173/node_modules/.vite/deps/react-router.js:6043:25
BrowserRouter@http://localhost:5173/node_modules/.vite/deps/react-router.js:8070:11
	printWarning (chunk-KDCVS43I.js:521)
	error (chunk-KDCVS43I.js:505)
	validateFunctionComponentInDev (chunk-KDCVS43I.js:15061)
	mountIndeterminateComponent (chunk-KDCVS43I.js:15036)
	beginWork$1 (chunk-KDCVS43I.js:19806)
	performUnitOfWork (chunk-KDCVS43I.js:19251)
	workLoopSync (chunk-KDCVS43I.js:19190)
	renderRootSync (chunk-KDCVS43I.js:19169)
	performConcurrentWorkOnRoot (chunk-KDCVS43I.js:18728:98)
	workLoop (chunk-KDCVS43I.js:197)
	flushWork (chunk-KDCVS43I.js:176)
	performWorkUntilDeadline (chunk-KDCVS43I.js:384)
```

### Affected component/components

DatePicker, Dialog

### How to reproduce

I simply copy/pasted examples code for those components in my code.

### Logs

```bash

```

### System Info

```bash
Macbook Pro M1Pro, Sequoia 15.4.1, Safari
```

### Before submitting

- [x] I've made research efforts and searched the documentation
- [x] I've searched for existing issues

**Comment by Sladerix** [comment]
I solved by updating React
`npm install --save-exact react@^19.0.0 react-dom@^19.0.0`

**Comment by walid1508** [comment]
Hey @Sladerix ,
I'm having the same issue,
but npm install --save-exact react@^19.0.0 react-dom@^19.0.0
still doesn't fix it on my end
![Image](https://github.com/user-attachments/assets/6c175711-057e-47b3-bb99-c334b72e6f95)

**Comment by walid1508** [comment]
Error :  react-dom.development.js:86 
 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of DataTableSearchBar.
    at Input (http://localhost:1420/src/components/ui/input.tsx:18:18)
    at div
    at div
    at DataTableSearchBar (http://localhost:1420/src/components/data-table/data-table-search-bar.tsx:23:3)
    at div
    at div
    at ErrorBoundary (http://localhost:1420/node_modules/.vite/deps/react-error-boundary.js?v=a46e66c6:18:5)


this is the code of input.tsx when i use cli 

![Image](https://github.com/user-attachments/assets/6a3d766a-92f0-46a1-abe5-922665d5ce76)

and this is the code of manual install

![Image](https://github.com/user-attachments/assets/74c8b41a-a568-4149-a124-02aefa670640)

**Comment by Sladerix** [comment]
@walid1508 I do not used Input component, unfortunately I do not know how to solve your issue.
(I know it's stupid, did you try to restart the project after updating react?)

**Comment by walid1508** [comment]
Yes, I restart my project after updating React.
To bypass the bug, I install the components manually rather than using the CLI.

**Comment by walid1508** [comment]
@Sladerix  Yeah, for now.

**Comment by dominictobias** [comment]
Why isn't e.g. Button given `forwardRef`, considering it breaks the Dropdown completely from working and e.g. theme `mode-toggle.tsx` in the docs and the Dropdown examples don't work?

**Comment by dominictobias** [comment]
> Why isn't e.g. Button given `forwardRef`, considering it breaks the Dropdown completely from working and e.g. theme `mode-toggle.tsx` in the docs and the Dropdown examples don't work?

Nevermind I thought I'd updated React 18->19 but hadn't. Now works without the change
