### ISSUE TITLE
[bug]: Type error with Form component when using Zod transform schema in React Hook Form v7.56.1

### ISSUE THREAD

**Issue by maroKanatani** [shadcn-ui/ui#7312]
### Describe the bug

When upgrading React Hook Form from v7.54.2 to v7.56.1, a type error occurs in the Form component when using Zod transform schema. The error appears specifically when trying to use transformed schema output types with FormField components.

### Affected component/components

FormField

### How to reproduce

1. Create a Zod schema with transform
2. Set up React Hook Form with the transformed schema
3. Try to use FormField components with the form
4. TypeScript compilation fails with type errors

Here's a minimal reproduction code:

```tsx
"use client"

import { zodResolver } from "@hookform/resolvers/zod"
import { useForm } from "react-hook-form"
import { z } from "zod"

import { Button } from "@/components/ui/button"
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form"
import { Input } from "@/components/ui/input"

const formSchema = z.object({
  firstName: z.string().min(1),
  lastName: z.string().min(1),
}).transform((data) => {
  return {
    fullName: `${data.firstName} ${data.lastName}`,
  }
})

export default function ProfileForm() {
  const form = useForm<z.input<typeof formSchema>, unknown, z.output<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      firstName: "",
      lastName: "",
    },
  })
 
  
  function onSubmit(values: z.infer<typeof formSchema>) {
    console.log(values)
  }

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-8">
        <FormField
          // typeError
          control={form.control}
          name="firstName"
          render={({ field }) => (
            <FormItem>
              <FormLabel>FirstName</FormLabel>
              <FormControl>
                <Input placeholder="shadcn" {...field} />
              </FormControl>
              <FormDescription>
                This is your public display name.
              </FormDescription>
              <FormMessage />
            </FormItem>
          )}
        />
         <FormField
          control={form.control}
          name="lastName"
          render={({ field }) => (
            <FormItem>
              <FormLabel>LastName</FormLabel>
              <FormControl>
                <Input placeholder="ui" {...field} />
              </FormControl>
              <FormDescription>
                This is your public display name.
              </FormDescription>
              <FormMessage />
            </FormItem>
          )}
        />
        <Button type="submit">Submit</Button>
      </form>
    </Form>
  )
}
```

Error Message
```
Type 'Control<{ firstName: string; lastName: string; }, unknown, { fullName: string; }>' is not assignable to type 'Control<{ firstName: string; lastName: string; }, any, { firstName: string; lastName: string; }>'.
```

I've verified that this works correctly with React Hook Form v7.54.2 but breaks after upgrading to v7.56.1. This seems to be related to how the Form component handles transformed schema types in the newer version of React Hook Form.

### Logs

```bash

```

### System Info

```bash
React Hook Form: 7.56.1
shadcn/ui: 2.5.0
React: 18.3.1
zod: 3.24.3
```

### Before submitting

- [x] I've made research efforts and searched the documentation
- [x] I've searched for existing issues

**Comment by hugues-m** [comment]
had the same problem but it seems to come from the `@hookform/resolvers` package

fixed it by reverting it to v4 `"@hookform/resolvers": "^4.1.3"`

now it's ok for us even with `"react-hook-form": "^7.56.2"`

**Comment by maroKanatani** [comment]
@hugues-m 
I tried downgrading `@hookform/resolvers` to v4.1.3 as suggested, but the type error persists.

```tsx

export default function ProfileForm() {
  const form = useForm<z.input<typeof formSchema>, unknown, z.output<typeof formSchema>>({
    resolver: zodResolver(formSchema), // typeError 
    defaultValues: {
      firstName: "",
      lastName: "",
    },
  })
```

```
Type 'Resolver<{ fullName: string; }>' is not assignable to type 'Resolver<{ firstName: string; lastName: string; }, unknown, { fullName: string; }>'.
  Types of parameters 'values' and 'values' are incompatible.
    Property 'fullName' is missing in type '{ firstName: string; lastName: string; }' but required in type '{ fullName: string; }'.ts(2322)
```


I found a working solution by modifying the `FormField` component's type definition to handle transformed values:

```diff
const FormField = <
  TFieldValues extends FieldValues = FieldValues,
  TName extends FieldPath<TFieldValues> = FieldPath<TFieldValues>,
+  TTransformedValues extends FieldValues = FieldValues
>({
  ...props
-}: ControllerProps<TFieldValues, TName>) => {
+}: ControllerProps<TFieldValues, TName, TTransformedValues>) => {
  return (
    <FormFieldContext.Provider value={{ name: props.name }}>
      <Controller {...props} />
    </FormFieldContext.Provider>
  )
}
```

**Comment by eriickz** [comment]
@maroKanatani it works for yup too.

**Comment by Jervx** [comment]
> 4.1.3

Thank you, reverting fixed mine as well, thanks.

**Comment by BradHacker** [comment]
Reverting to 4.1.3 fixed mine too.

Also downgrading react-hook-form to 7.54.2 fixed the issue as well.

**Comment by nicojs** [comment]
I can confirm this error also exists when using `z.coerce`.

```ts
export const Pokemon = z.object({
  name: z.string(),
  level: z.coerce.number<string>().min(1).max(100),
});
export type Pokemon = z.infer<typeof Pokemon>;
```

**Comment by zhzhang** [comment]
There's an issue on the `react-hook-form` repo that mentions not to pass the type parameters to `useForm` in more recent versions, as the input and output types will resolve themselves to the right values. This fixed the issue for me.
Unfortunately, I've lost the link to that discussion :(

**Comment by kryptoblack** [comment]
Starting in v7.55.0-next.8, React Hook Form added the TTransformedValues generic to support resolvers that change the shape of the data (for example, Zod transforms). This is a good addition, but it also means that wrappers around Controller need to pass this third generic argument. The current shadcn-ui FormField only forwards the first two generics, which causes type errors whenever the output type differs from the input type.

PR #8223 updates the types to support TTransformedValues, but it has not been merged yet.

What is the recommended approach until this is resolved upstream?

• Should we temporarily patch the shadcn-ui components locally to accept the third generic?
• Or should we keep RHF and @hookform/resolvers pinned to a version before this change?
• Is there any update on when PR #8223 might be merged or if a different fix is planned?
