### ISSUE TITLE
[bug]: Problem copy and paste in components examples

### ISSUE THREAD

**Issue by rafaelRizzo** [shadcn-ui/ui#8071]
### Describe the bug

I started a project today and tried to copy a component directly from the official website, i.e.: https://ui.shadcn.com/docs/components/checkbox, and it simply doesn't work. Nothing happens.

### Affected component/components

All

### How to reproduce

When I click on code, select all the content, and use the CTRL + C shortcut, it doesn't work. I can't copy any components. I have to right-click, go to the context menu, and click copy. Previously, there was a copy option. Is there a way to restore this?

### Logs

```bash

```

### System Info

```bash
Windows 11
```

### Before submitting

- [x] I've made research efforts and searched the documentation
- [x] I've searched for existing issues

**Comment by VishalBhat07** [comment]
Hi, I was able to reproduce this issue on Windows 11 as well — when copying code snippets from the docs with `Ctrl + C`, nothing happens. Right-click → Copy still works, but the usual copy functionality is broken.  

I’d be happy to work on a fix. Could you confirm if the intended solution is to restore the copy button on code blocks?

**Comment by rafaelRizzo** [comment]
The intention would be to copy not everything as in the copy shortcut that is in the "copy all code" components, only copy what was selected with `CTRL + C`.

**Comment by rafaelRizzo** [comment]
Apparently it was resolved after the last MCP server change.

**Comment by infoflowtech** [comment]
Nope, was not resolved. Still happening (Nov, 29, 2025, Win-11, Chrome).

**Comment by rtabulov** [comment]
the bug still exists, why is this closed?
