### ISSUE TITLE
[bug]: Select component reopens on second tap instead of closing (touch devices)

### ISSUE THREAD

**Issue by GravityTwoG** [shadcn-ui/ui#8813]
### Describe the bug

On touch devices, when the Select component's options list is open, a second tap on the trigger component reopens the list instead of closing it. I think the expected behavior is for the second tap on the trigger to close the  options list.

Link to component preview:
https://ui.shadcn.com/docs/components/select

Video with the problem:

https://github.com/user-attachments/assets/5003910f-5fb1-4bc3-bc10-f1ce71ee293d

### Affected component/components

Select

### How to reproduce

1. Open [Select component preview](https://ui.shadcn.com/docs/components/select) in mobile browser or using mobile mode in chrome-based browser devtools.
2. Tap on trigger to open options list.
3. Tap on different point inside trigger component. (If you'll tap on the same point, then options will close as expected)

### Codesandbox/StackBlitz link

The reproduction is on the shadcn's website https://ui.shadcn.com/docs/components/select

### Logs

```bash

```

### System Info

```bash
Reproduced in Chrome browser on android, devtools in mobile mode in Arc browser.
```

### Before submitting

- [x] I've made research efforts and searched the documentation
- [x] I've searched for existing issues

**Comment by nehaaprasad** [comment]
Hello! @GravityTwoG 
fixed it, please let me know!

**Comment by GravityTwoG** [comment]
Thanks for the response, @naaa760

Unfortunately, the issue still persists for me. 

However, I discovered that the issue is observed more often when taps are slightly longer in mobile mode. If I tap quickly, everything works correctly. But when I tap and hold little bit longer, it reopens again. On a real phone, Select reopens almost always.

Also, it seems that handleTouchStart is not called on the second tap:

https://github.com/user-attachments/assets/f35ba524-c375-4843-9273-06b7b296fe2f

**Comment by nehaaprasad** [comment]
@GravityTwoG 
please check , I fixed it sorry for being a late.

**Comment by GravityTwoG** [comment]
Hello, @naaa760. I have tested the fix, but the problem is still there. The onPointerDown and onClick handlers are not called on the second tap
